// <auto-generated />
using System;
using KAST.Infratructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KAST.Infratructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("KAST.Domain.Entities.Faction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Delete")
                        .HasColumnType("TEXT");

                    b.Property<string>("Flag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<int>("UseSide")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("KAST.Domain.Entities.Fireteam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Delete")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InviteOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RestrictTeamCompoition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SquadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SquadId");

                    b.ToTable("Fireteams");
                });

            modelBuilder.Entity("KAST.Domain.Entities.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Delete")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissionBriefingLink")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("MissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Template")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Worldanme")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("KAST.Domain.Entities.MissionUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Delete")
                        .HasColumnType("TEXT");

                    b.Property<int>("MissionID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SquadID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MissionID");

                    b.HasIndex("SquadID");

                    b.HasIndex("UserID");

                    b.ToTable("MissionUsers");
                });

            modelBuilder.Entity("KAST.Domain.Entities.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("KAST.Domain.Entities.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Delete")
                        .HasColumnType("TEXT");

                    b.Property<int>("FireteamID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValideted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MissionUserID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FireteamID");

                    b.HasIndex("MissionUserID");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("KAST.Domain.Entities.Squad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Delete")
                        .HasColumnType("TEXT");

                    b.Property<int>("FactionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameSide")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxUsuerCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissionID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SquadPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FactionID");

                    b.HasIndex("MissionID");

                    b.ToTable("Squads");
                });

            modelBuilder.Entity("KAST.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Delete")
                        .HasColumnType("TEXT");

                    b.Property<string>("EMail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<int>("MissionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("SteamID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SteamName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KAST.Domain.Entities.Fireteam", b =>
                {
                    b.HasOne("KAST.Domain.Entities.Squad", "Squad")
                        .WithMany("Fireteams")
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Squad");
                });

            modelBuilder.Entity("KAST.Domain.Entities.MissionUser", b =>
                {
                    b.HasOne("KAST.Domain.Entities.Mission", "Mission")
                        .WithMany("Users")
                        .HasForeignKey("MissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KAST.Domain.Entities.Squad", "Side")
                        .WithMany("MissionUsers")
                        .HasForeignKey("SquadID");

                    b.HasOne("KAST.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Side");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KAST.Domain.Entities.Slot", b =>
                {
                    b.HasOne("KAST.Domain.Entities.Fireteam", "Fireteam")
                        .WithMany("Slots")
                        .HasForeignKey("FireteamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KAST.Domain.Entities.MissionUser", "AssignedUser")
                        .WithMany("Slots")
                        .HasForeignKey("MissionUserID");

                    b.Navigation("AssignedUser");

                    b.Navigation("Fireteam");
                });

            modelBuilder.Entity("KAST.Domain.Entities.Squad", b =>
                {
                    b.HasOne("KAST.Domain.Entities.Faction", "Faction")
                        .WithMany("Squads")
                        .HasForeignKey("FactionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KAST.Domain.Entities.Mission", "Mission")
                        .WithMany("squads")
                        .HasForeignKey("MissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("KAST.Domain.Entities.Faction", b =>
                {
                    b.Navigation("Squads");
                });

            modelBuilder.Entity("KAST.Domain.Entities.Fireteam", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("KAST.Domain.Entities.Mission", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("squads");
                });

            modelBuilder.Entity("KAST.Domain.Entities.MissionUser", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("KAST.Domain.Entities.Squad", b =>
                {
                    b.Navigation("Fireteams");

                    b.Navigation("MissionUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
